TRUNCATE generators CASCADE;
TRUNCATE langs CASCADE;
TRUNCATE tests CASCADE;
TRUNCATE tasks CASCADE;
TRUNCATE test_tasks CASCADE;
TRUNCATE translations CASCADE;
TRUNCATE phrases CASCADE;
TRUNCATE results CASCADE;